return {
  arrows = {
    ArrowRight = "?",
    ArrowLeft = "?",
    -- ChevronRight = "?",
    ChevronRight = ">",
    CurvedArrowRight = "? ",
    DoubleArrowRight = "È",
    SmallArrowRight = "?",
    Diamond = "<>",
  },
  ui = {
    BigCircle = "? ",
    BigUnfilledCircle = "? ",
    BookMark = "? ",
    Bug = "? ",
    Calendar = "? ",
    Check = "? ",
    Circle = "? ",
    Close = "? ",
    Code = "? ",
    Comment = "? ",
    Dashboard = "? ",
    Fire = "? ",
    Gear = "? ",
    History = "? ",
    Lightbulb = "? ",
    List = "? ",
    Lock = "? ",
    NewFile = "? ",
    Note = "? ",
    Package = "? ",
    Pencil = "? ",
    Plus = "+",
    Project = "? ",
    RunningMan = "??",
    Search = "? ",
    SignIn = "? ",
    Table = "? ",
    Telescope = "? ",
    Yoga = "??",
    Xmark = "?",
  },
  diagnostics = {
    Error = "? ",
    Hint = "? ",
    Information = "? ",
    Question = "? ",
    Warning = "? ",
  },
  git = {
    Add = "? ",
    Diff = "? ",
    Ignore = "? ",
    Mod = "? ",
    Remove = "? ",
    Rename = "? ",
    Repo = "? ",
  },
}
